server:
  port: 8090

spring:
  redis:
    timeout: 60000 #连接超时时间（毫秒）
    database: 0 #Redis数据库索引（默认为0）
    cluster: # 集群节点
      nodes:
        - 192.168.230.24:6379
        - 192.168.230.24:6380
        - 192.168.230.24:6381
        - 192.168.230.24:6389
        - 192.168.230.24:6390
        - 192.168.230.24:6391
    lettuce:
      pool:
        max-active: 1000  #连接池最大连接数（使用负值表示没有限制）
        max-idle: 10 # 连接池中的最大空闲连接
        min-idle: 5 # 连接池中的最小空闲连接
        max-wait: -1 # 连接池最大阻塞等待时间（使用负值表示没有限制）